name: PR validation

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pip install poetry

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: 'poetry'

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('**/playwright.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install dependencies
        run: |
          poetry install
          poetry run playwright install

      - name: pre-commit
        run: |
          poetry run pre-commit run -a

      - name: pytest check
        run: |
          poetry run pytest
